# Generated by Django 5.2.5 on 2025-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie_images/')),
                ('is_current', models.BooleanField(default=False)),
                ('preview_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
